### Requisição para a raiz da API
GET http://localhost:5043

### Listar Empresa
GET http://localhost:5043/empresa/listar

### Buscar Empresa
GET http://localhost:5043/empresa/buscar/3

### Cadastrar Empresa
POST http://localhost:5043/empresa/cadastrar/
Content-Type: application/json

{
    "Nome" : "Twitter",
    "Cnpj" : "333-111",
    "Endereco" : "rua armando penaltas"
}

### Alterar Empresa
PUT http://localhost:5043/empresa/alterar/11
Content-Type: application/json

{
    "Nome": "Empresa Modificada",
    "Cnpj": "3333-33",
    "Endereco": "butiatuvinha"
}

### Deletar Empresa
DELETE http://localhost:5043/empresa/deletar/10

// ------------------------------------------------------ //
### Listar Serviço
GET http://localhost:5043/servico/listar

### Buscar Serviço
GET http://localhost:5043/servico/buscar/2

### Cadastrar Serviço
POST http://localhost:5043/servico/cadastrar/
Content-Type: application/json

{
    "Nome" : "Twitter",
    "TipoServico" : "333-111",
    "Valor" : "rua armando penaltas",
    "DataContratacao" : "12/02"
}

### Alterar Serviço
PUT http://localhost:5043/servico/alterar/11
Content-Type: application/json

{
    "tipoServico": "Serviço Modificada",
    "valor": "33.30",
    "dataContratacao": "10/01"
}

### Deletar Serviço
DELETE http://localhost:5043/servico/deletar/10

// ------------------------------------------------------ //
### Listar Funcionario

GET http://localhost:5043/funcionario/listar

### Buscar Empresa
GET http://localhost:5043/funcionario/buscar/1

### Cadastrar Empresa
POST http://localhost:5043/funcionario/cadastrar/
Content-Type: application/json

{
    "Nome" : "Jonathan",
    "Cargo" : "Mecanico",
    "Contato" : "inta 22"
}

### Alterar Empresa
PUT http://localhost:5043/funcionario/alterar/4
Content-Type: application/json

{
    "Nome" : "Maicon",
    "Cargo" : "Encanador",
    "Contato" : "Zap 42"
}

### Deletar Empresa
DELETE http://localhost:5043/funcionario/deletar/5


