@base_url = http://localhost:5043

### Requisição para a raiz da API
GET http://localhost:5043

### Listar Empresa
GET {{base_url}}/empresa/listar

### Buscar Empresa
GET {{base_url}}/empresa/buscar/3

### Cadastrar Empresa
POST {{base_url}}/empresa/cadastrar/
Content-Type: application/json

{
    "Nome" : "Twitter",
    "Cnpj" : "333-111",
    "Endereco" : "rua armando penaltas"
}

### Alterar Empresa
PUT {{base_url}}/empresa/alterar/11
Content-Type: application/json

{
    "Nome": "Empresa Modificada",
    "Cnpj": "3333-33",
    "Endereco": "butiatuvinha"
}

### Deletar Empresa
DELETE {{base_url}}/empresa/deletar/9

// ------------------------------------------------------ //
### Listar Serviço
GET {{base_url}}/servico/listar

### Buscar Serviço
GET {{base_url}}/servico/buscar/2

### Cadastrar Serviço
POST {{base_url}}/servico/cadastrar/
Content-Type: application/json

{
    
    "Nome" : "Twitter",
    "TipoServico" : "333-111",
    "Valor" : "rua armando penaltas",
    "DataContratacao" : "12/02"
}

### Alterar Serviço
PUT {{base_url}}/servico/alterar/11
Content-Type: application/json

{
    "tipoServico": "Serviço Modificada",
    "valor": "33.30",
    "dataContratacao": "10/01"
}

### Deletar Serviço
DELETE {{base_url}}/servico/deletar/10

// ------------------------------------------------------ //
### Listar Funcionario

GET {{base_url}}/funcionario/listar

### Buscar Funcionario
GET {{base_url}}/funcionario/buscar/1

### Cadastrar Funcionario
POST {{base_url}}/funcionario/cadastrar/
Content-Type: application/json

{
    "Nome" : "Jonathan",
    "Cargo" : "Mecanico",
    "Contato" : "inta 22"
}

### Alterar Funcionario
PUT {{base_url}}/funcionario/alterar/2
Content-Type: application/json

{
    "Nome" : "Maicon",
    "Cargo" : "Encanador",
    "Contato" : "Zap 42"
}

### Deletar Funcionario
DELETE {{base_url}}/funcionario/deletar/1


