// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto_desenvolvimento_software_visual.Models;

#nullable disable

namespace projeto_desenvolvimento_software_visual.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241111182033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("projeto_desenvolvimento_software_visual.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("projeto_desenvolvimento_software_visual.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("projeto_desenvolvimento_software_visual.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataContratacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmpresaClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FuncionarioResponsavelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoServico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("FuncionarioResponsavelId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("projeto_desenvolvimento_software_visual.Models.Servico", b =>
                {
                    b.HasOne("projeto_desenvolvimento_software_visual.Empresa", "EmpresaCliente")
                        .WithMany("ServicosContratados")
                        .HasForeignKey("EmpresaClienteId");

                    b.HasOne("projeto_desenvolvimento_software_visual.Models.Funcionario", "FuncionarioResponsavel")
                        .WithMany()
                        .HasForeignKey("FuncionarioResponsavelId");

                    b.Navigation("EmpresaCliente");

                    b.Navigation("FuncionarioResponsavel");
                });

            modelBuilder.Entity("projeto_desenvolvimento_software_visual.Empresa", b =>
                {
                    b.Navigation("ServicosContratados");
                });
#pragma warning restore 612, 618
        }
    }
}
